### ISSUE TITLE
Error: The file is not displayed in the text editor because it is a directory.

### ISSUE THREAD

**Issue by ZobaJakColbert** [Pedro-Bronsveld/anki-editor#3]
Some note types can't be open and I've got this error "The file is not displayed in the text editor because it is a directory."

![obraz](https://github.com/Pedro-Bronsveld/anki-editor/assets/57141103/67dba852-6f88-423e-87df-043b642a26d5)

**I think the problem is with card's templates that are ending with "?" sign**

The icons next to Front and Back are different.
Non-working icons (problematic card's templates) in VS
![obraz](https://github.com/Pedro-Bronsveld/anki-editor/assets/57141103/1dc363e5-0541-40f2-b5dc-6be6523b47db)

Working icons in VS
![obraz](https://github.com/Pedro-Bronsveld/anki-editor/assets/57141103/a997430d-b314-4422-9410-db723ff93903)

**Comment by Pedro-Bronsveld** [comment]
I've tested this and it does indeed seem to be a problem with the "?" in the name of a card templates.
I'll see if I can fix it.

Interestingly, this problem doesn't occur when you open the note types as a workspace folder using the button in the top right corner of the anki-editor column. So you could use that as a workaround for now.

**Comment by Pedro-Bronsveld** [comment]
This has been fixed and published in version 1.0.4 .
