### ISSUE TITLE
Anki-editor for Ankidroid

### ISSUE THREAD

**Issue by ZobaJakColbert** [Pedro-Bronsveld/anki-editor#4]
Is there a way to use your anki-editor (or any solution) to edit cards and see changes on Ankidroid?

**Comment by Pedro-Bronsveld** [comment]
Right now there's no way to do this.

However, I did have a look at this project: [AnkiconnectAndroid](https://github.com/KamWithK/AnkiconnectAndroid), which implements a number of the Anki-Connect api actions on Android.

I tried to use it with Anki Editor, but some of Anki-Connect's actions aren't implemented in the api yet.
I was able to get the main list of note types to load in VSCode, but then the `"modelTemplates"` action is required to retrieve the card template contents for a note type. And that action hasn't been implemented.

That project is open to contributors so if anyone has the time to implemented the missing actions that Anki Editor depends on, it could work.

Also, if your goal is to test CSS changes specific to Android, there's an option labeled "Add Mobile Class" in the drop-down at the top right of Anki's template editor preview window. That will enable the [mobile device css classes](https://docs.ankiweb.net/templates/styling.html#platform-specific-css) in the preview window.
